name: Alert CI

on:
  push:
    branches:
      - main
    paths:
      - 'alert/**/*.kt'

jobs:
  alert-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build Alert
        working-directory: ./alert
        run: ./gradlew build

      - name: Test Alert
        working-directory: ./alert
        run: ./gradlew test
