name: Batch CI

on:
  push:
    branches:
      - main
    paths:
      - 'batch/**/*.kt'

jobs:
  batch-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Batch
        working-directory: ./batch
        run: ./gradlew build

      - name: Test Batch
        working-directory: ./batch
        run: ./gradlew test
