name: Core CI

on:
  push:
    branches:
      - main
    paths:
      - 'core/**/*.kt'

jobs:
  core-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set ENV
        run: |
            mkdir -p core/src/main/resources
            echo "${{ secrets.ENV_YML }}" | base64 --decode > core/src/main/resources/application-env.yml
            mkdir -p core/src/test/resources
            echo "${{ secrets.ENV_YML }}" | base64 --decode > core/src/test/resources/application-env.yml

      - name: Build Core
        working-directory: ./core
        run: ./gradlew build

      - name: Test Core
        working-directory: ./core
        run: ./gradlew test
